### ISSUE TITLE
eH-reduce-data-array TODO

### ISSUE THREAD

**Issue by ragmha** [ragmha/eggHead#1]
- [ ] Use case for reduceRight 🤔
  - [ ] More examples of reduce 🤔
  - [ ] Look into composition 🤔
  - [ ] Try more nested object 🤔
